// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-pE-gqAdGhHU7mkbKIHH4PJaKM_BfDlU',
    appId: '1:1079250387330:web:a6ec8c67f94dd6fd694f9b',
    messagingSenderId: '1079250387330',
    projectId: 'programacionmovil-a2fff',
    authDomain: 'programacionmovil-a2fff.firebaseapp.com',
    storageBucket: 'programacionmovil-a2fff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYR9vHWT5zewrYdFdiUOQmyL_n58-WNGc',
    appId: '1:1079250387330:android:084a04fab44516c3694f9b',
    messagingSenderId: '1079250387330',
    projectId: 'programacionmovil-a2fff',
    storageBucket: 'programacionmovil-a2fff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5iaB8D3K9kjVnbIXXe58tNDwqyPmoevw',
    appId: '1:1079250387330:ios:6586a1ade0401c15694f9b',
    messagingSenderId: '1079250387330',
    projectId: 'programacionmovil-a2fff',
    storageBucket: 'programacionmovil-a2fff.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5iaB8D3K9kjVnbIXXe58tNDwqyPmoevw',
    appId: '1:1079250387330:ios:6586a1ade0401c15694f9b',
    messagingSenderId: '1079250387330',
    projectId: 'programacionmovil-a2fff',
    storageBucket: 'programacionmovil-a2fff.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-pE-gqAdGhHU7mkbKIHH4PJaKM_BfDlU',
    appId: '1:1079250387330:web:c07401fdc0eb122e694f9b',
    messagingSenderId: '1079250387330',
    projectId: 'programacionmovil-a2fff',
    authDomain: 'programacionmovil-a2fff.firebaseapp.com',
    storageBucket: 'programacionmovil-a2fff.firebasestorage.app',
  );
}
